### ISSUE TITLE
Can I use freesasa to calculate the SASA for a 3D small molecules?

### ISSUE THREAD

**Issue by chf42** [mittinatten/freesasa#40]
Hi,

I was trying to use this tool to calculate the SASA for a 3D small molecule, especially for some specific atoms in the molecule. I saved the molecule into pdb file with Pymol, and loaded using freesasa python API. 
>>> import freesasa
>>> structure = freesasa.Structure("1.pdb")
I got the error: 
FreeSASA:lib\src\structure.c:679: error: input had no valid ATOM or HETATM lines
FreeSASA:lib\src\structure.c:686: error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "freesasa.pyx", line 457, in freesasa.Structure.__init__
Exception: Error reading '1.pdb'.

Would you mind help me figure out how to generate valid PDB file of a given 3D small molecule for this program?

Thank you!

Cheng

**Comment by mittinatten** [comment]
Not sure if I can help you, not a Pymol expert, but if you post the pdb
here, I can maybe tell where the problem lies.
